fisa-algorithm-study/study-repo

README.md
=> [Docs] : Readme 수정

Python/주민경/[Week 1]자료구조/[BOJ] 풍선 터뜨리기_2346_실버3.py, Python/주민경/[Week 1]자료구조/[PGS] 올바른 괄호_LV2.py
[BOJ / PGS] 주민경 / 1주차 
-   문제 이름: 풍선 터뜨리기
-   플랫폼: 백준 
- 아이디어: 풍선 배열을 만들고, 터진 풍선일 경우 단계가 0보다 작으면 계속 index를 -1씩 하고, 0보다 크면  +1씩 하자. 
- 풀고 나니 터진 풍선을 아예 배열에서 제거하는 것이 더 편리하겠다는 생각이 듦.   
-   문제 이름: 올바른 괄호
-   플랫폼: 프로그래머스 
- 아이디어: 스택을 사용하여 "("를 넣음. 배열을 돌다가 ")"를 만나면 "("가 들어있는 스택에서 pop을 한다. 만약 "("가 부족하거나 남으면 올바른 괄호가 아니기 떄문에 False를 출력함 
=> [BOJ / PGS]  주민경 / 1주차

Java/양채연/[Week 1]자료구조/[BOJ] 풍선 터뜨리기_2346_실버3.java, Java/양채연/[Week 1]자료구조/[PGS] 올바른 괄호_LV2.java
[BOJ, PGS] 양채연 / 1주차
-   문제 이름: 풍선 터뜨리기, 올바른 괄호
-   플랫폼: 백준, 프로그래머스
- 풍선 터뜨리기 : 
배열로 노력하다가 너무 힘들어서 지피티 친구에게 도움을 받았습니다.. 
- 올바른 괄호 : 
이것도 배열로 풀었는데 스택을 쓰라고 되어 있어서 변경했습니다 그래도 방식은 똑같았어요
자료구조 공부를 해야겠습니다...
=> [BOJ, PGS] 양채연 / 1주차

Python/이종혁/[Week 1]자료구조/[BOJ] 풍선 터뜨리기_2346_실버3.py, Python/이종혁/[Week 2]자료구조 2/[BOJ]과제_13904_골드3.py, Python/이종혁/[Week 2]자료구조 2/[BOJ]단어공부_1157_브론즈1.py, Python/이종혁/[Week 2]자료구조 2/[SEA]스도쿠검증_1974_D2.py
[BOJ/SEA] 이종혁 / 2주차
-   문제 이름: 단어공부_1157_브론즈1
-   플랫폼: BOJ
- 딕셔너리 자료형을 이용해서 각각 문자에 대해 빈도수 체크
- 언패킹으로 dict.items() 할당(파이썬은 언패킹으로 시작해서 언패킹으로 끝나는듯..)
- 언패킹.
---
-   문제 이름: 스도쿠검증_1974
-   플랫폼: SEA
- 리스트 컴프리헨션으로 test_case 2차원 배열로 바꿔주기(이거 안해서 계속 에러뜸..)
- Set 자료구조 이용해서 중복검사 했습니다.
- 행, 열, 3x3 따로따로 검사했는데, 3x3배열은 현진씨 풀이보고 아이디어를 얻었습니다..(시작 좌표[BOJ/SEA] 이종혁 / 2주차
-   문제 이름: 단어공부_1157_브론즈1
-   플랫폼: BOJ
- 딕셔너리 자료형을 이용해서 각각 문자에 대해 빈도수 체크
- 언패킹으로 dict.items() 할당(파이썬은 언패킹으로 시작해서 언패킹으로 끝나는듯..)
- 언패킹.
---
-   문제 이름: 스도쿠검증_1974
-   플랫폼: SEA
- 리스트 컴프리헨션으로 test_case 2차원 배열로 바꿔주기(이거 안해서 계속 에러뜸..)
- Set 자료구조 이용해서 중복검사 했습니다.
- 행, 열, 3x3 따로따로 검사했는데, 3x3배열은 현진씨 풀이보고 아이디어를 얻었습니다..(range(start : …
=> [BOJ/SEA] 이종혁 / 2주차

Java/조원희/[Week 2]자료구조2/[BOJ] 과제_13904_골드3.java, Java/조원희/[Week 2]자료구조2/[BOJ] 단어 공부_1157_브론즈1.java, Java/조원희/[Week 2]자료구조2/[SEA] 스도쿠 검증_1974_D2.java
-   문제 이름: 단어 공부
-   플랫폼: 백준
- HashMap Key의 중복 저장이 안되는 것을 이용해서 알파벳을 저장하고자 하였다.
- 이때 Character의 아스키 코드를 이용해서 대소문자를 비교하고자 하였다.
-   [0] 예제 입력/출력 통과
-   [0] 모든 테스트 케이스 통과
-   [0] 목표 시간 이내 해결
- map.getOrDefault( )을 사용하면 코드를 좀 더 줄일 수 있다. 
---------------------------------
-   문제 이름: 스도쿠 검증
-   플랫폼: SW Expert Academy
- swea의 문제들은 D4 전까지는 빡 구현이 많은 것을 알고 있었다.
- 그렇기에 좀 더 효율적이게 풀수 있을까를 생각해 보았지만, 하나하나 구현하는 것이 더 좋다고 생각해서
- 다음과 같이 구현했다. 
- 해당 문제도 Hashset를 이용해서 중복 저장이 안되는 것을 이용했다.
-   [0] 예제 입력/출력 통과
-   [0] 모든 테스트 케이스 통과
-   [0] 목표 시간 이내 해결
--------------------------------
-   문제 이름: 과제
-   플랫폼: 백준
-  해당 문제를 해결하기 위해서는 과제의 마지막 날에서부터 접근을 해야 하는 것을 알 수 있었을 것이다.
- 나는 해당 문제를 자료구조 하나만 사용하여 해결하고 싶었기에 index을 값을 알 수 있는 ArrayList를 사용해서 해결했다.
- 하지만 PiriorityQueue를 사용해서 푸는 문제라고 하니 PiriorityQueue도 사용해서 풀어보고자 했을 때는, …
=> [BOJ] / [SEA]  조원희 / 2주차

Java/양채연/[Week 2]자료구조2/[BOJ] 단어 공부_1157_브론즈1.java, Java/양채연/[Week 2]자료구조2/[SEA] 스도쿠 검증_D2.java
[BOJ/SEA] 양채연 / 2주차
-   문제 이름: 단어공부
-   플랫폼: 백준
-   배열로 풀지 말자고 해서 맵으로 풀었음 value에 대한 key를 얻는 방법을 몰라서 시간을 좀 썼어요
Map.Entry를 통해 key-value 객체로 key 값을 얻어냈습니다
-   문제 이름: 스도쿠 검증
-   플랫폼: 삼성
-   중복 걸러내는 set함수로 가로 / 세로 / 3*3 검사하는 방법을 사용했습니다
풀이 방식에 대한 접근은 어렵지 않았지만 for문 중첩을 잔뜩해서 이게 맞는지 잘모르겠습니다
사실 아직 에러가 납니다,,,  고쳐보겠음
=> [BOJ/SEA] 양채연 / 2주차

Java/임건애/[Week 2]자료구조2/[BOJ] 과제_13904_골드3.java, Java/임건애/[Week 2]자료구조2/[BOJ] 단어 공부_1157_브론즈1.java, Java/임건애/[Week 2]자료구조2/[SEA] 스도쿠 검증_1974_D2.java
[BOJ/SEA] 임건 / 2주차
- 문제 이름: 단어 공부
- 플랫폼: BOJ
이전에 배열로 풀어봤던걸 Map으로 바꿔서 풀어주었습니다
-
x
- 문제 이름: 스도쿠 검증
- 플랫폼: SEA
이전에 배열로 풀어봤던걸 Set으로 조금 바꿔주었습니다  
-
x
- 문제 이름: 과제
- 플랫폼: BOJ
우선순위 큐로 풀어보다가 정렬이 맘대로 안 돼서 배열로 바꿔보았으나 아직 못 풀었습니다  
- 
-   [ ] 예제 입력/출력 통과
못 풀었습니다...어렵네요
=> [BOJ/SEA] 임건애 / 2주차

Python/이종혁/[Week 2]자료구조 2/[BOJ]단어공부_1157_브론즈1.py, Python/이종혁/[Week 3]자료구조_3/[BOJ]나는야포켓몬마스터_1620_실버4.py, Python/이종혁/[Week 3]자료구조_3/[BOJ]영단어암기는괴로워_20920_실버3.py, README.md
[BOJ] 이종혁 / 3주차
-   문제 이름:[BOJ]나는야포켓몬마스터_1620_실버4
-   플랫폼:BOJ
- 푸킷몬의 이름과 도감번호를 각각 key로 저장하는 defaultdict 두개 선언해주었다.
- 문제는 그냥 list로 입력받았고 isdigit() 메소드로, 문제가 숫자라면 dict에서 도감번호로 푸킷몬 찾고, 푸킷몬 이름이라면 도감번호를 출력한다.
--- 
-   문제 이름:[BOJ]영단어암기는괴로워_20920_실버3
-   플랫폼:BOJ
- 일단 문제 하단의 Note대로, readine으로 풀었는데, input으로 다시 푸니까 시간초과남.
- 정렬의 연속..
- 빈도수 계산은 딕셔너리로 단어 리스트 순회하면서 체크했다.
- lambda문법은 반드시 꼭 구글링 없이도 풀 수 있도록 숙지해야겠다..
-   [x] 목표 시간 이내 해결(input()은 시간초과)
=> [BOJ] 이종혁 / 3주차

Java/조원희/[Week 3]자료구조3/[BOJ] 영단어 암기는 어려워_20920_실버3.java, Java/조원희/[Week 3]자료구조3/[BOJ] 포켓몬_1620_실버4.java
-   문제 이름: 나는야 포켓몬 마스터 이다솜
-   플랫폼: 백준
- 자료구조 하나만 써볼려고 했는데 시간 초과...
- 더 나은 방법이 생각이 안나서 자료구조 2개 썼다.
-   [X] 예제 입력/출력 통과
-   [X] 모든 테스트 케이스 통과
-   [X] 목표 시간 이내 해결
- 먼가 하나만 쓰는 방법이 있을거 같은데...
-   문제 이름: 영단어 암기는 어려워
-   플랫폼: 백준
- HashMap의 중복 불가를 이용해서 단어의 개수를 찾고,
- List에 Node를 만들어서 map에 있는 값을 넣어주고 정렬했다
-   [X] 예제 입력/출력 통과
-   [X] 모든 테스트 케이스 통과
-   [X] 목표 시간 이내 해결
- Entry 쓰기 싫어..
=> [BOJ] 조원희 / 3주차

Java/임건애/[Week 3] 자료구조/[BOJ] 영단어_20920_실버3.java, Java/임건애/[Week 3] 자료구조/[BOJ] 포켓몬_1620_실버4.java
[BOJ] 임건애 / 3주차
-   문제 이름: 나는야 포켓몬 마스터 이다솜
-   플랫폼: BOJ
보자마자 Map이 떠올라서 Map으로 풀었습니다  
M 만큼 포켓몬 이름이나 도감 번호를 받을 때, 숫자인지 문자열인지 판별하는 게 어려웠어요  
검색해보니까 예외처리를 해도 되고 정규식을 사용해도 된대서 정규식을 사용해보았습니다 (사실 어려워서 이해는 아직 안 됐어요)  
처음에는 포켓몬 이름이 주어졌을 때 반복문으로 도감에서 포켓몬을 찾았는데, 시간 복잡도를 줄여보자! 해서 그냥 Map을 두개 사용하는 방법으로 바꿔주었습니다  
-   문제 이름: 영단어 암기는 괴로워
-   플랫폼: BOJ
우선 단어의 빈도수를 세어야 겠다고 생각해서 단어를 key로, 빈도수를 value로 갖는 Map을 썼습니다  
지난 주에 원희가 알려준 방법으로 코드 길이를 줄일 수 있었어요  
그리고 우선순위 정렬? 오 이거 저번주에 원희가 알려줬던 건데! 써보자! 해서 단어 String을 갖는 List를 만들고 Comparator를 사용해서 풀어주었습니다  
문자열 사전순 비교는 어려워서 검색해보았는데 compareTo()를 사용하면 된대요  
마지막 출력을 그냥 for문 안에 println을 했을 때 시간 초과가 나서 StringBuilder로 값을 받고 출력해주는 걸로 바꿔주었더니 해결되었습니다
=> [BOJ] 임건애 / 3주차

Python/정용준/[Week 3]/[BOJ]나는야_포켓몬_마스터_이다솜_1620_실버4.py, Python/정용준/[Week 3]/[BOJ]영단어_암기는_어려워._20920_실버3.py
-   문제 이름: [BOJ] 나는야 포켓몬 마스터  1620 실버 4
-   플랫폼: BOJ
- 배열과 딕셔너리를 이용해서 키값을 찾는다. isdigit() [숫자인가?]메소드로 작성한.
---
-   문제 이름:[BOJ] 영단어 암기는 괴로워 20920 실버3
-   플랫폼: [BOJ]
- 카운터로 풀려고 했으나 정렬 에서 이해되지 않아 찾아봄
카운터로 풀려고 했으나 정렬 에서 이해되지 않아 찾아봄
=> [BOJ] 정용준 / 3주차

Java/임건애/[Week 4]트리/[BOJ] 트리 순회_1991_실버1.java
[BOJ] 임건애 / 4주차
-   문제 이름: 트리 순회
-   플랫폼: BOJ
노드 클래스 만들어서 구현했습니다...
=> [BOJ] 임건애 / 4주차

Java/조원희/[Week 4]트리/[BOJ] 양 구출 작전_16437_골드3.java, Java/조원희/[Week 4]트리/[BOJ] 트리 순회_1991_실버1.java, Java/조원희/[Week 4]트리/[BOJ] 트리의 부모 찾기_11725_실버2.java, Java/조원희/[Week 4]트리/[BOJ] 트리인가_6416_undefined.java
-   문제 이름: 트리인가?
-   플랫폼: 백준
- 예외 처리가 까다로웠던 문제
- 트리가 구성되어야 할 조건들을 생각하고 이를 하나씩 걸러줘야했다.
왜 0 0만 들어올 때 트리인가?
-------------------------------------------------------------------------------------------------
-   문제 이름: 트리의 부모 찾기
-   플랫폼: 백준
- 그래프 문제를 풀어본 사람이 있다면 쉽게 풀었을 문제
- tree 기준으로 어떤 노드로 먼저 들어가야 한다는 내용이 없다면 다음과 같은 방식으로 풀면 좋다.
-------------------------------------------------------------------------------------------------
-   문제 이름: 트리의 순회
-   플랫폼: 백준
- 해당 문제도 트리의 부모 찾기와 비슷하다 middle, left, right를 모두 주었기에
- Arraylist에 집어 넣을때 left -> right 순으로 집어 넣는다면
- for(int key: map.get(number))를 했을 때 left -> right 순으로 탐색 가능 
-   [x] 목표 시간 이내 …
=> [BOJ] 조원희 / 4주차

Java/이정복/[Week 4]트리/[BOJ] 트리 순회_1191_실버1.java, Java/이정복/[Week 4]트리/[BOJ] 트리의 부모 찾기_11725_실버2.java, Java/이정복/[Week 4]트리/[BOJ] 트리인가_6416_Unranked.java
[BOJ] 이정복 / 4주차
---
-   문제 이름:  트리인가?
-   플랫폼: BOJ
1. 루트 노드는 하나만 존재한다.
- 진입차수가 0인 노드가 없거나 2개 이상 있으면 트리 아님
2. 루트를 제외한 모든 노드는 부모노드를 하나만 갖는다. (진입 차수를 1만 갖는다.)
- 진입차수가 2 이상인 노드가 있으면 트리 아님
3. 트리에는 사이클이 있으면 안된다.
- 트리 순회 중 방문한 노드를 다시 방문했다면 트리 아님
4. 모든 노드는 연결되어 있어야 한다.
- 트리 순회가 완료되었는데 방문하지 않은 노드가 있다면 트리 아님
이 문제를 처음 풀어서 클래스 이름이나 자료구조가 엉망진창입니다..
1, 2번은 진입차수를 측정해서 확인했고 3, 4번은 순회하면서 확인했습니다.
---
-   문제 이름: 트리 순회
-   플랫폼: BOJ
- 전위, 중위, 후위 탐색 알고리즘을 작성하는 문제였습니다.
- 전에 푼 문제는 반복문 형식으로 풀어서 재귀적으로 풀어보려고 했습니다.
---
-   문제 이름: 트리의 부모 찾기
-   플랫폼: BOJ
- 트리를 bfs 순회하며 부모 리스트를 채우는 방식으로 풀었습니다.
처음에는 노드마다 bfs 알고리즘을 돌렸는데 시간초과가 떠서 한번의 bfs에서 …
=> [BOJ] 이정복 / 4주차

Java/조원희/[Week 5]완전 탐색/[BOJ] 바이러스_2606_실버3.java, Java/조원희/[Week 5]완전 탐색/[BOJ] 분해합_2231_브론즈2.java, Java/조원희/[Week 5]완전 탐색/[BOJ] 블랙잭_2798_브론즈2.java, Java/조원희/[Week 5]완전 탐색/[PGS] 소수 찾기_Level2.java, Java/조원희/[Week 5]완전 탐색/[PGS] 전력망을 둘로 나누기_Level2.java, Java/조원희/[Week 6]수학, 백트래킹/[BOJ] N과 M (1)_15649_실버3.java, Java/조원희/[Week 6]수학, 백트래킹/[BOJ] 더하기 사이클_1110_브론즈1.java, Java/조원희/[Week 6]수학, 백트래킹/[BOJ] 부분수열의 합_1182_실버2.java, Java/조원희/[Week 7]그리디/[BOJ] 문서 검색_1543_실버5.java, Java/조원희/[Week 7]그리디/[BOJ] 카약과 강풍_2891_실버4.java, Java/조원희/[Week 7]그리디/[BOJ} 거스름돈_14916_실버5.java, Java/조원희/[Week 7]그리디/[PGS] 체육복_Level1.java
-   문제 이름: 블랙잭
-   플랫폼: 백준
- 3중 for문..?
- 3중 for문 아닌거 같은데..
---
-   문제 이름: 분해합
-   플랫폼: 백준
- 1~N 까지 돌아도 O(N)..
---
-   문제 이름: 소수 찾기
-   플랫폼: 프로그래머스
- vistired[ ] 이용해서 모든 경로 찾기
---
-   문제 이름: 바이러스
-   플랫폼: 백준
- 그래프 문제
--
-   문제 이름: 전력망 둘로 나누기
-   플랫폼: 프로그래머스
- 그래프 문제에서 조금 더 나아가서 간선을 막아보자
=> [BOJ/PGS] 5주차 조원희

Java/임건애/[Week 5]완전 탐색/[BOJ] 분해합_2231_브론즈2.java, Java/임건애/[Week 5]완전 탐색/[BOJ] 블랙잭_2798_브론즈2.java, Java/임건애/[Week 5]완전 탐색/[PGS] 소수 찾기_42839_LV2.java
[BOJ/PGS] 5주차 임건애
-   문제 이름: 블랙잭
-   플랫폼: BOJ
오름차순으로 정렬하고 반복문 세개 돌면서 합이 M을 넘으면 result에 값이 더 담기지 않게 했어요
-   문제 이름: 분해합
-   플랫폼: BOJ
그냥 완전 탐색 했어요
-   문제 이름: 소수 찾기
-   플랫폼: PGS
수 조합을 어떻게 만들어야 될 지 고민을 많이 했는데  
전역변수 Set 만들어두고 substring으로 재귀 돌려서 만들어봤어요...
=> [BOJ/PGS] 5주차 임건애

Python/이종혁/[Week 5]완전 탐색/[PGS] 전력망을둘로나누기_LV2.py, Python/이종혁/[Week 6]수학_백트래킹/[BOJ]N과M(1)_15649_실버3.py, Python/이종혁/[Week 6]수학_백트래킹/[BOJ]더하기사이클_1110_브론즈1.py, Python/이종혁/[Week 6]수학_백트래킹/[BOJ]부분수열의합_1182_실버2.py, Python/이종혁/[Week 6]수학_백트래킹/[BOJ]에라토스테네스의체_2960_실버5.py, Python/이종혁/[Week 7]그리디/[BOJ]거스름돈_14916_실버5.py, Python/이종혁/[Week 7]그리디/[BOJ}문서검색_1543_실버5.py, Python/이종혁/[Week 7]그리디/[PGS]체육복_LV1.py
=> [BOJ/PGS] 이종혁 / 6,7주차

Java/조원희/[Week 6]수학, 백트래킹/[BOJ] 에라토스테네스의 체_2960_실버4.java, Java/조원희/[Week 7]그리디/[BOJ] 등수 매기기_2012_실버3.java
[BOJ/PGS] 7주차 조원희
-   문제 이름: 거스름돈
-   플랫폼: BOJ
- 재귀 + 그리디 방식으로 풀고 flag를 두어 분기를 막았다.
- 굳이 재귀로 안풀어도 됐을듯
---
-   문제 이름: 문서 검색
-   플랫폼: BOJ
- startsWith()와 substring을 써서 해결
---
-   문제 이름: 체육복
-   플랫폼: PGS
- 최소 메모리로 풀려고 노력했다.
---
-   문제 이름: 카약과 강풍
-   플랫폼: BOJ
- 체육복 문제와 같은 방식으로 해결
---
-   문제 이름: 등수매기기
-   플랫폼: BOJ
- long 타입 빼먹지 않기...
---
=> [BOJ/PGS] 6/7주차 조원희

Java/임건애/[Week 7]그리디/[BOJ] 거스름돈_14916_실버5.java, Java/임건애/[Week 7]그리디/[BOJ] 등수 매기기_2012_실버3.java, Java/임건애/[Week 7]그리디/[BOJ] 문서 검색_1543_실버5.java, Java/임건애/[Week 7]그리디/[BOJ] 카약과 강풍_2891_실버4.java, Java/임건애/[Week 7]그리디/[PGS] 체육복_42862_LV1.java
[BOJ/PGS] 7주차 임건애
- 문제 이름: 거스름돈
- 플랫폼: BOJ
큰 돈 5원으로 지불할 수 있는 최대 개수를 구하고 그 개수에서 하나씩 빼가면서 2원으로 나눠 떨어지는지 확인했습니다  
x
- 문제 이름: 문서 검색
- 플랫폼: BOJ
`substring` 해가면서 푸는 문제인가? 했는데  
String.class 레퍼런스를 찾아보다가 `replaceAll` 메서드가 눈에 띄었어요  
그걸로 푸니까 너무 간편했습니다..
x
- 문제 이름: 체육복
- 플랫폼: PGS
카약 문제를 먼저 풀어서 동일하게 풀었습니다  
x
- 문제 이름: 카약과 강풍
- 플랫폼: BOJ
카약을 1개씩은 갖고있는 N 크기의 팀 배열을 만들고 손상되면 --, 여분이 있으면 ++로 세팅해주었습니다  
그리고 반복문이랑 조건문을 돌면서 직접 비교해주었어요  
x
- 문제 이름: 등수매기기
- 플랫폼: BOJ
입력받은 예상 등수를 오름차순 정렬하고 절대값 계산해서 더해주기만 했는데 맞았어요  
정답이라고 뜨긴 했는데 이렇게 푸는 게 맞는지는 모르겠습니다..  
-   [x] 예제 입력/출력 …
=> [BOJ/PGS] 7주차 임건애

Java/조원희/[Week 8]그리디/[BOJ] 강의실 배정_11000_골드4.java, Java/조원희/[Week 8]그리디/[PGS] 섬 연결하기_Level3.java, Java/조원희/[Week 8]그리디/[PGS] 지붕잃고 외양간 고치기_Level0.java
-   문제 이름: 강의실 배정
-   플랫폼: 백준
- 정렬 문제 + 우선 순위 큐 문제로 기존 배정 문제와는 다르게
- 강의실을 열어야 하는 조건이 생겨 이를 우선 순위 큐로 이용해서 해결함 
---
-   문제 이름: 섬 연결하기
-   플랫폼: 프로그래머스
- BFS + 그리디로 해결
-   [X] 모든 테스트 케이스 통과
-   [X] 목표 시간 이내 해결
---
-   문제 이름: 지붕 잃고 외양간 고치기
-   플랫폼: 프로그래머스
- gap을 찾는 아이디어
=> [BOJ/PGS] 8주차 조원희

Java/조원희/[Week 9]DP/[BOJ] 1로 만들기_1463_실버3.java, Java/조원희/[Week 9]DP/[BOJ] 다리 놓기_1010_실버5.java
9주차 DP
-   문제 이름: 다리 놓기
-   플랫폼: 백준
- 조합론에 대해서 안다면 접근이 쉬웠지만 몰랐다면 오래 걸릴 문제
---
-   문제 이름: 1로 만들기
-   플랫폼: 백준
- DP 배열을 생성 후 조건에 맞게 넣어 top-down 방식 사용
=> [BOJ] 9주차 조원희

Java/양채연/[Week 10]DP2/[BOJ] 가장 긴 증가하는 부분 수열_11053_실버2.java, Java/양채연/[Week 11]Heap, UnionFind/[BOJ] 최대 힙_11279_실버2.java, Java/양채연/[Week 11]Heap, UnionFind/[BOJ] 최소 힙_1927_실버2.java, Java/양채연/[Week 11]Heap, UnionFind/[PGS] 더 맵게_Level2.java
=> [BOJ, PGS] 10주차, 11주차 양채연
